// CODEBASE-MAP.md: one generated page, budgeted, that a session reads instead of grepping.
//
// lean-v2 B11. The index this renders from already pays for itself — 90% recall at a 96.5% token
// reduction on the golden queries, 3,397 tokens against 97,995 — and nothing used it, because
// nothing said it existed and nothing kept it current. A map is a guide; a guide nobody is
// pointed at steers nobody.
//
// One page, not a wiki. `lib/wiki.mjs` rendered per-cluster markdown for eleven days and no
// change's evidence ever cited a page. What a reader opens, and what SessionStart can summarise
// in two lines, is a single ranked map.

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { query } from './graph.mjs';

export const MAP_FILE = 'CODEBASE-MAP.md';
export const MAX_LINES = 200;

export const mapPath = (cfg) => path.join(cfg.layout.root, MAP_FILE);

// A module's role, in one line, from what it exports rather than from prose someone has to
// maintain. The first exported symbol is nearly always the module's reason to exist.
function role(g, rel) {
  const m = g.modules[rel];
  if (!m) return '';
  const names = m.symbols.slice(0, 3).map((s) => s.name);
  return names.length ? names.join(', ') : `${m.imports.length} import(s)`;
}

export function render(g, { max = MAX_LINES, now = null } = {}) {
  const modules = Object.keys(g.modules);
  const hubs = query(g, 'hubs', null, { limit: 20 });
  const cycles = query(g, 'cycles', null, {});

  const lines = [
    `<!-- Generated by \`harness map\`; do not edit. ${modules.length} modules, ${Object.values(g.modules).reduce((n, m) => n + m.symbols.length, 0)} symbols. -->`,
    '# Codebase map',
    '',
    'Where things are, ranked by how much depends on them. Ask the index before you grep:',
    '',
    '```',
    'harness graph query callers <symbol>      who breaks if this changes',
    'harness graph query calls <symbol>        what this depends on',
    'harness graph query hubs                  the load-bearing modules',
    'harness graph query cycles                where the structure knots',
    'harness pack <symbol>                     a token-budgeted slice of context',
    '```',
    '',
    '## Load-bearing modules',
    '',
    '| Module | Depended on by | Exports |',
    '|---|---:|---|',
  ];

  for (const h of hubs) {
    if (lines.length >= max - 12) break;
    lines.push(`| \`${h.module}\` | ${h.fan_in} | ${role(g, h.module)} |`);
  }

  if (cycles.length) {
    lines.push('', '## Cycles', '', 'Each of these is a knot: changing one member means reading all of them.', '');
    for (const c of cycles.slice(0, 10)) {
      if (lines.length >= max - 4) break;
      lines.push(`- ${c.map((m) => `\`${m}\``).join(' → ')}`);
    }
  }

  // "Start here": the biggest modules by symbol count, which is where a reader lands anyway.
  const biggest = Object.entries(g.modules)
    .sort((a, b) => b[1].symbols.length - a[1].symbols.length)
    .slice(0, 3);
  if (biggest.length) {
    lines.push('', '## Start here', '');
    for (const [rel, m] of biggest) lines.push(`- \`${rel}\` — ${m.symbols.length} symbols: ${role(g, rel)}`);
  }

  if (now) lines.push('', `<!-- rendered ${now} -->`);

  // The budget is a hard stop, not a target. A map that grows with the codebase stops being
  // something a session can afford to read, which is the only reason it exists.
  return lines.slice(0, max).join('\n') + '\n';
}

// The two lines SessionStart injects. Cheap enough to pay on every session.
export function summary(cfg, g) {
  const hubs = query(g, 'hubs', null, { limit: 5 }).map((h) => h.module);
  const written = existsSync(mapPath(cfg));
  return [
    `map:    ${written ? MAP_FILE : `${MAP_FILE} not written — run: harness map`}  (${Object.keys(g.modules).length} modules)`,
    hubs.length ? `hubs:   ${hubs.join(', ')}` : 'hubs:   none — no intra-project imports found',
  ];
}

export function write(cfg, g, opts = {}) {
  const body = render(g, opts);
  writeFileSync(mapPath(cfg), body);
  return { file: mapPath(cfg), lines: body.split('\n').length };
}

// Drift is the committed map disagreeing with the tree. Returned rather than thrown so the Stop
// hook can record a verdict either way: `graph-refresh` recorded 57 invocations and zero fires
// because it could only ever pass, which is indistinguishable from a control that checks nothing.
export function drift(cfg, g) {
  const file = mapPath(cfg);
  if (!existsSync(file)) return { drifted: true, reason: `${MAP_FILE} has never been written` };
  const committed = readFileSync(file, 'utf8');
  const fresh = render(g);
  if (committed === fresh) return { drifted: false };

  const was = committed.split('\n');
  const is = fresh.split('\n');
  const gone = was.filter((l) => l.startsWith('| `') && !is.includes(l)).slice(0, 3);
  const added = is.filter((l) => l.startsWith('| `') && !was.includes(l)).slice(0, 3);
  return {
    drifted: true,
    reason: `${MAP_FILE} is stale`,
    gone: gone.map((l) => l.split('`')[1]),
    added: added.map((l) => l.split('`')[1]),
  };
}
