// The playbook asks that alignment between the diff and the plan be measured. This enforces it:
// a changed file that no approved committed plan claims is a finding.
//
// lean-v2 B5 moved ownership to `## Files` in `plan.md`. It used to live in a contract section
// called `## Structure and ownership`, and the plan's hand-written list was checked against a
// diff the tooling could already compute — which is how ten of twenty-three contracts came to be
// re-sealed for a missing line. One source now, in the artifact a human approved.
//
// a-plan-proves-its-spec B7 (evidence.md F25) lives here too: B2 checks, at approval, only that a
// spec's behaviours each have a Proof row — a plan may legitimately name a test it has not
// written yet. This is that promise checked at the only moment the answer is knowable, so it runs
// unconditionally, not only when the current diff happens to touch a product file.

import { existsSync } from 'node:fs';
import path from 'node:path';
import * as artifacts from '../lib/artifacts.mjs';
import { gateBlocks } from '../lib/config.mjs';
import { changedFiles, git, unbornRepository } from '../lib/diff.mjs';

const under = (file, owned) => file === owned || file.startsWith(owned.replace(/\/$/, '') + '/');

// G06. Each finding says which gate it belongs to, and the gate's mode decides whether this
// control fails the stage or annotates it. One verdict per control, so a blocking finding wins:
// `unkept-proof` carries no gate at all — an approved plan naming a test that does not exist is
// a broken promise in a gate that was already given, not a gate still waiting for an answer, and
// no mode relaxes it.
function verdictFor(cfg, findings) {
  if (!findings.length) return 'pass';
  const blocking = findings.some((f) => !f.gate || gateBlocks(cfg, f.gate));
  return blocking ? 'fail' : 'warn';
}

// The gate tag is internal routing, not part of the finding schema the report renders and the
// normalisers fill. Stripped once the verdict is computed so `render` and the ledger see exactly
// the shape they saw before this change.
const shed = (findings) => findings.map(({ gate, ...f }) => f);

const graded = (cfg, findings) => ({ verdict: verdictFor(cfg, findings), findings: shed(findings) });

// B7: for every plan this repository's approval currently governs, each Proof row naming a test
// file must name one that exists. Presence-only rows (B2's bar) and prose evidence are not this
// check's business — `testRowIn` returns null for those, same as `behavioursHaveTests` already
// relies on.
function unkeptProof(cfg, plans) {
  const findings = [];
  for (const plan of plans) {
    const body = artifacts.read(cfg, plan.slug, 'plan')?.body ?? '';
    for (const [behaviour, evidence] of artifacts.proofRowsOf(body)) {
      const row = artifacts.testRowIn(evidence);
      if (!row) continue;
      let present = existsSync(path.join(cfg.layout.root, row.file));
      if (cfg.diff) {
        try { present = git(cfg.layout.root, ['cat-file', '-t', `${cfg.diff.candidate}:${row.file}`]).trim() === 'blob'; }
        catch { present = false; }
      }
      if (present) continue;
      findings.push({
        file: `.aidlc/artifacts/${plan.slug}/plan.md`, line: 0, rule: 'unkept-proof',
        message: `${behaviour}: proof row names "${row.file}", which does not exist`,
        fix: `write ${row.file} with the test it promises, or correct the Proof row and re-approve the plan`,
      });
    }
  }
  return findings;
}

export async function run(cfg) {
  if (unbornRepository(cfg)) return { verdict: 'skipped', findings: [], note: 'no commits yet; local scope requires HEAD' };
  const changed = changedFiles(cfg);

  const plans = artifacts.governingPlans(cfg);
  const proofFindings = unkeptProof(cfg, plans);

  // The artifacts themselves are always writable. A gate you cannot draft is not a gate.
  // CODEBASE-MAP.md is harness output, regenerated by the Stop hook (every-control-fires-or-goes
  // B5); no plan should have to claim what the harness writes.
  const ignore = (f) => f.startsWith('.aidlc/artifacts/') || f.startsWith('.aidlc/state/') || f === 'CODEBASE-MAP.md';
  const product = changed.filter((f) => !ignore(f));
  if (!product.length && !cfg.diff) {
    return graded(cfg, proofFindings);
  }

  // Approved, committed, and unchanged since approval. An uncommitted approval is not an
  // auditable gate, and an approved plan whose body has since been edited is a stale approval —
  // `governingPlans` drops both, so a plan cannot widen its own scope after the fact.
  const owned = [...new Set(plans.flatMap((p) => p.owns))];

  // Distinguish unavailable selection from the selected change's own pending gate.
  if (!plans.length) {
    const current = artifacts.currentChange(cfg);
    const drafts = artifacts.draftsAwaitingGate(cfg);
    // a-draft-is-a-declaration B3: a written, unapproved spec is work declared and not gated.
    const finding = drafts.length
      ? {
          gate: drafts[0].kind === 'plan' ? 'plan' : 'spec',
          rule: 'draft-awaits-gate',
          message: `changed while ${artifacts.awaitingGateLine(drafts[0]).replace(/^awaiting/, 'awaiting')}${drafts.length > 1 ? ` (also: ${drafts.slice(1).map((d) => `${d.slug}/${d.kind}.md`).join(', ')})` : ''} — ${drafts[0].slug}/${drafts[0].kind}.md`,
          fix: artifacts.awaitingGateRemedy(drafts[0]),
        }
      : current
      ? {
          gate: 'plan',
          rule: 'no-approved-plan',
          message: `changed under the current change "${current.slug}" — ${artifacts.currentLine(cfg)}`,
          fix: artifacts.currentLine(cfg),
        }
      : {
          // Nothing is selected, so nothing has reached gate 2 yet: gate 1 is what is missing.
          gate: 'spec',
          rule: 'no-current-change',
          message: `changed with no executable selection — ${artifacts.currentLine(cfg)}`,
          fix: 'harness status --change <slug>; approve its spec and plan and commit each',
        };
    return graded(cfg, [...(product.length ? product : ['.aidlc/artifacts/']).map((f) => ({ file: f, line: 0, ...finding })), ...proofFindings]);
  }

  // A plan that claims nothing governs nothing, and would silently authorise the whole tree.
  const empty = plans.filter((p) => !p.owns.length).map((p) => ({
    file: `.aidlc/artifacts/${p.slug}/plan.md`, line: 0, gate: 'plan', rule: 'plan-scope-missing',
    message: 'an approved plan declares no owned files',
    fix: 'list every path this change may touch, in backticks, under "## Files"',
  }));
  if (empty.length) return graded(cfg, [...empty, ...proofFindings]);

  const findings = [
    ...product
      .filter((f) => !owned.some((d) => under(f, d)))
      .map((f) => ({
        file: f, line: 0, gate: 'plan', rule: 'scope-drift',
        message: `changed but not named by the current change "${plans[0].slug}" — its plan's ## Files does not claim it`,
        fix: `add the path to "## Files" of ${plans[0].slug}/plan.md and re-approve it, or revert the change`,
      })),
    ...proofFindings,
  ];

  return graded(cfg, findings);
}
